export const POST_ESTACIONES_LIST_SUCCESS = "POST_ESTACIONES_LIST_SUCCESS";
export const POST_ESTACIONES_LIST_FAIL = "POST_ESTACIONES_LIST_FAIL";

export const POST_CACHE_LIST_SUCCESS = "POST_CACHE_LIST_SUCCESS";
export const POST_CACHE_LIST_FAIL = "POST_CACHE_LIST_FAIL";
