export const POST_ESTACIONES_LIST_SUCCESS = "POST_ESTACIONES_LIST_SUCCESS";
export const POST_ESTACIONES_LIST_FAIL = "POST_ESTACIONES_LIST_FAIL";

export const GET_CACHE_LIST_SUCCESS = "GET_CACHE_LIST_SUCCESS";
export const GET_CACHE_LIST_FAIL = "GET_CACHE_LIST_FAIL";
